artifact_location: /home/deli_fo/projects/object_detection/patch_generation/patch_generation/runs/mlflow/941758277464791073
creation_time: 1709636221859
experiment_id: '941758277464791073'
last_update_time: 1709636221859
lifecycle_stage: active
name: /Shared/YOLOv8
