artifact_location: /home/deli_fo/projects/object_detection/patch_generation/patch_generation/runs/mlflow/0
creation_time: 1709636221853
experiment_id: '0'
last_update_time: 1709636221853
lifecycle_stage: active
name: Default
